name: Convert Markdown to HTML

on:
  push:
    branches:
      - main
    paths:
      - '**.md'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Pandoc
        run: |
          sudo apt update
          sudo apt install -y pandoc 	

      - name: Convert MD to HTML
        run: |
          mkdir -p html_files
          for file in *.md; do
            pandoc --standalone "$file" -o "html_files/${file%.md}.html"
          done

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add html_files/*.html  # Adjust the path to match where your HTML files are
          git commit -m "Convert MD files to HTML" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_TOKEN }}
          branch: main

      - name: Push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          git commit -m "Convert MD files to HTML" || echo "No changes to commit."
          git push --set-upstream origin ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }} # or use your PAT: ${{ secrets.MY_PERSONAL_TOKEN }}    

